"""add unique constraint to posts news_id

Revision ID: e3221797005d
Revises: 9a3b4c5d6e7f
Create Date: 2026-07-28 18:29:17.541370

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e3221797005d'
down_revision: Union[str, Sequence[str], None] = '9a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_news_id'), table_name='posts')
    op.create_index(op.f('ix_posts_news_id'), 'posts', ['news_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_news_id'), table_name='posts')
    op.create_index(op.f('ix_posts_news_id'), 'posts', ['news_id'], unique=False)
    # ### end Alembic commands ###
